// Generated by CoffeeScript 1.12.6
(function() {
  var Redis, debug, plugin, redis_url;

  Redis = require('ioredis');

  debug = (require('debug'))('tangible:redis');

  redis_url = process.env.TANGIBLE_REDIS;

  module.exports = plugin = function(w) {
    var Notepack, client, encode;
    if (redis_url == null) {
      return;
    }
    client = new Redis(redis_url);
    encode = (function() {
      switch (process.env.TANGIBLE_ENCODE) {
        case 'notepack.io':
          Notepack = require('notepack.io');
          return function(data) {
            return Notepack.encode(data);
          };
        default:
          return function(data) {
            return JSON.stringify(data);
          };
      }
    })();
    w.on('debug', function(data) {
      return client.publish('tangible:debug', encode(data))["catch"](function(error) {
        return debug("publish: " + error.stack);
      });
    });
  };

}).call(this);
